name: clusteroids
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  firebase_core: ^2.30.1
  cupertino_icons: ^1.0.8
  hexcolor: ^3.0.1
  font_awesome_flutter: ^10.7.0
  flutter_login: ^5.0.0
  otp_text_field: ^1.1.3
  firebase_app_check: ^0.2.2+4
  charts_flutter: ^0.12.0
  provider: ^6.1.2
  image_picker: ^1.1.1
  firebase_storage: ^11.7.4
  file_picker: ^8.0.3
  dio: ^5.4.3+1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
